version: '3'

services:
  backend:
    build: backend
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=12345678
      - DATABASE_SECRET=12345678
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_NAME=find_a_match
    depends_on:
      - database
  
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  database:
    build: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=find_a_match